Add custom SDK url

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -103,6 +103,14 @@ inputs:
     required: false
     type: string
     default: ''
+  custom-sdk-url:
+    required: false
+    type: string
+    default: ''
+  custom-sdk-id:
+    required: false
+    type: string
+    default: ''
 
 runs:
   using: "composite"
@@ -320,7 +328,7 @@ runs:
           exit 1
         fi
 
-        if [[ "${{ inputs.installed-sdk }}" != '' ]]; then
+        if [ "${{ inputs.installed-sdk }}" != '' ] && [ "${{ inputs.custom-sdk-url }}" == '']; then
           # we already have an SDK installed
           SWIFT_SDK_TARGET="${{ inputs.installed-sdk }}"
           echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV
@@ -330,29 +338,42 @@ runs:
           mkdir -p ${RUNNER_TEMP}/swift-android-toolchain
           cd ${RUNNER_TEMP}/swift-android-toolchain
 
-          SWIFT_SDK_ID="${{ steps.setup.outputs.swift-id }}"
-          # TODO: identify the version automatically
-          SWIFT_SDK_VERSION="0.1"
+          ANDROID_SDK_URL="${{ inputs.custom-sdk-url }}"
           SWIFT_SDK_ARCH="${{ steps.setup.outputs.android-sdk-arch }}"
 
-          # 6.0.x-6.1 (but not 6.1.1)
-          if [[ "${SWIFT_SDK_ID}" =~ "-6.0" || "${SWIFT_SDK_ID}" =~ "-6.1-" ]]; then
-            # Swift Android SDK 6.0/6.1 targets API 24+
-            SWIFT_SDK_ANROID_API="24"
-            SWIFT_SDK_ID="${SWIFT_SDK_ID}-android-${SWIFT_SDK_ANROID_API}-${SWIFT_SDK_VERSION}"
+          if [[ "${ANDROID_SDK_URL}" != '' ]]; then
+            if [ "${{ inputs.installed-sdk }}" == '' ] || [ "${{ inputs.custom-sdk-id }}" == '' ]; then
+              echo "::error::Options 'custom-sdk-id' and 'installed-sdk' must be provided when downloading custom SDK."
+              exit 1
+            fi
+
+            SWIFT_SDK_TARGET="${{ inputs.installed-sdk }}"
+            echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV
+            SWIFT_SDK_ID="${{ inputs.custom-sdk-id }}"
           else
-            # Swift Android SDK 6.1.1+ targets API 28+
-            SWIFT_SDK_ANROID_API="28"
-            # 6.2+ no longer includes the API in the artifactbundle name
-            SWIFT_SDK_ID="${SWIFT_SDK_ID}-android-${SWIFT_SDK_VERSION}"
+            # TODO: identify the version automatically
+            SWIFT_SDK_VERSION="0.1"
+            SWIFT_SDK_ID="${{ steps.setup.outputs.swift-id }}"
+
+            # 6.0.x-6.1 (but not 6.1.1)
+            if [[ "${SWIFT_SDK_ID}" =~ "-6.0" || "${SWIFT_SDK_ID}" =~ "-6.1-" ]]; then
+              # Swift Android SDK 6.0/6.1 targets API 24+
+              SWIFT_SDK_ANROID_API="24"
+              SWIFT_SDK_ID="${SWIFT_SDK_ID}-android-${SWIFT_SDK_ANROID_API}-${SWIFT_SDK_VERSION}"
+            else
+              # Swift Android SDK 6.1.1+ targets API 28+
+              SWIFT_SDK_ANROID_API="28"
+              # 6.2+ no longer includes the API in the artifactbundle name
+              SWIFT_SDK_ID="${SWIFT_SDK_ID}-android-${SWIFT_SDK_VERSION}"
+            fi
+            ANDROID_SDK_URL="https://github.com/skiptools/swift-android-toolchain/releases/download/${{ steps.setup.outputs.swift-version }}/${SWIFT_SDK_ID}.artifactbundle.tar.gz"
+
+            SWIFT_SDK_TARGET="${SWIFT_SDK_ARCH}-unknown-linux-android${SWIFT_SDK_ANROID_API}"
+            echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV
           fi
-          ANDROID_SDK_URL="https://github.com/skiptools/swift-android-toolchain/releases/download/${{ steps.setup.outputs.swift-version }}/${SWIFT_SDK_ID}.artifactbundle.tar.gz"
 
           echo "ANDROID_SDK_URL: ${ANDROID_SDK_URL}"
           curl -fsSL --retry 8 --retry-connrefused ${ANDROID_SDK_URL} --output ${SWIFT_SDK_ID}.artifactbundle.tar.gz
-
-          SWIFT_SDK_TARGET="${SWIFT_SDK_ARCH}-unknown-linux-android${SWIFT_SDK_ANROID_API}"
-          echo "SWIFT_SDK_TARGET=${SWIFT_SDK_TARGET}" >> $GITHUB_ENV
 
           # first check if it already installed (we may be running this workflow multiple times for an action, in which case it will already be present)
           ${SWIFT_INSTALLATION}/bin/swift sdk configure --show-configuration ${SWIFT_SDK_ID} ${SWIFT_SDK_TARGET} &> /dev/null || ${SWIFT_INSTALLATION}/bin/swift sdk install ${SWIFT_SDK_ID}.artifactbundle.tar.gz
