Handle exit code EXIT_NO_TESTS_FOUND (69) when Testing finds no test cases (see https://github.com/swiftlang/swift-package-manager/issues/8362#issuecomment-2719173349)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -375,7 +375,11 @@ runs:
             # see https://github.com/swiftlang/swift-package-manager/issues/8362#issuecomment-2719116854
             # but only do it when the command links to the Testing library, otherwise it will fail with the error:
             # Error: Invalid option "--testing-library"
-            patchelf --print-needed ${XCTEST} | grep libTesting.so && TEST_SHELL="${TEST_SHELL} && ${TEST_CMD} --testing-library swift-testing" || true
+            #
+            # We additionally need to handle the special exit code EXIT_NO_TESTS_FOUND (69 on Android),
+            # which can happen when the tests link to Testing, but no tests are executed
+            # see: https://github.com/swiftlang/swift-package-manager/blob/1b593469e8ad3daf2cc10e798340bd2de68c402d/Sources/Commands/SwiftTestCommand.swift#L1542
+            patchelf --print-needed ${XCTEST} | grep libTesting.so && TEST_SHELL="${TEST_SHELL} && ${TEST_CMD} --testing-library swift-testing && [ $? -eq 0 ] || [ $? -eq 69 ]" || true
           fi
           echo "adb shell '${TEST_SHELL}'" >> ${SCRIPT_FILE}
         done
